### ISSUE TITLE
Fancy dropdown items

### ISSUE THREAD

**Issue by imalsogreg** [reflex-frp/reflex-dom-semui#1]
I'm trying to replace my ad-hoc use of semui classes with `reflex-dom-semui`.

<img width="389" alt="screen shot 2016-10-06 at 11 56 23 pm" src="https://cloud.githubusercontent.com/assets/993484/19178629/7453f3c6-8c22-11e6-9517-07ee2c5dff4e.png">

A menu-item here is a several-line `MonadWidget` action that splits the item into a pair of `<span>`s to separately decorate. To get this in `reflex-dom-semui` would we need one of your `semUiDropdown` functions to take an argument `Dynamic t (Map a (m ()))` rather than `Dynamic t (Map a Text)`?

**Comment by mightybyte** [comment]
Yeah, that sounds reasonable.  This dropdown stuff needs a lot of expansion.  Maybe add a new function instead of changing the existing one.

**Comment by imalsogreg** [comment]
21324ac89bcda8b7b4484209c7846e80ce895c9a
