### ISSUE TITLE
Use jsaddle instead of stubbing

### ISSUE THREAD

**Issue by 3noch** [reflex-frp/reflex-dom-semui#10]

**Comment by hamishmack** [comment]
Oh I had a go at doing this a while back to check what (if anything was missing in JSaddle).  But I did not have time to check if the code actually worked. I'll send a pull request as it might still be a good starting point.

**Comment by hamishmack** [comment]
I have sent a [pull request](https://github.com/reflex-frp/reflex-dom-semui/pull/11) that seems to build ok for me, but I have still not tested that the JSaddle code actually works (although it should work at least as well as the stubs did).

**Comment by 3noch** [comment]
@hamishmack Awesome! I never dreamed the work would already be started (and maybe mostly finished)!
