### ISSUE TITLE
Checkbox ignores inital value

### ISSUE THREAD

**Issue by andrewthad** [reflex-frp/reflex-dom-semui#15]
One of the fields in `CheckboxConfig` is [`_checkboxConf_initialValue`](https://github.com/reflex-frp/reflex-dom-semui/blob/a14b615d10b334772afb43472d9f2154fa4f7707/src/Reflex/Dom/SemanticUI/Checkbox.hs#L88). This field is not ever used.

**Comment by mightybyte** [comment]
Yeah, I recently merged that PR from @tomsmalley.  I didn't take the time to test it.

**Comment by tomsmalley** [comment]
Sorry about that! Fixed in #16.

**Comment by mightybyte** [comment]
Merged, thanks!
