### ISSUE TITLE
Checkbox Immidiately Unchecks Itself

### ISSUE THREAD

**Issue by andrewthad** [reflex-frp/reflex-dom-semui#19]
I have a checkbox that looks like this:

      let isChecked = True
      cb <- uiCheckbox (text "") (def
        { R._checkboxConf_type = [CbToggle]
        , R._checkboxConf_attributes = bool M.empty (M.singleton "checked" "checked") isChecked
        , R._checkboxConf_initialValue = isChecked
        })

This works, but it's kind of a shame that I need to have `_checkboxConf_attributes` in there. If I do not add that in, the checkbox immidiately fires a change event and sets itself to `False` when the page loads.

**Comment by tomsmalley** [comment]
The examples contain a similar checkbox and it appears to be working for me. Do you see the same behaviour here? https://reflex-frp.github.io/reflex-dom-semui/
source: https://github.com/reflex-frp/reflex-dom-semui/blob/master/example/Main.hs#L89
I don't currently have the ghcjs toolchain installed but should be able to have a deeper look soon.

**Comment by 3noch** [comment]
I have used the checkbox initial value but I haven't seen this.

**Comment by 3noch** [comment]
Fixed by #23

**Comment by mightybyte** [comment]
Thanks for the heads-up!
