### ISSUE TITLE
Use jQuery API in compatability mode

### ISSUE THREAD

**Issue by 3noch** [reflex-frp/reflex-dom-semui#25]
Use `jQuery` instead of `$` in FFI. This works in more contexts.

**Comment by 3noch** [comment]
Wow that was fast! Thanks for doing this. Would it not be best to do the same change in the jsaddle code too?

**Comment by mightybyte** [comment]
Oh, where's that?  I didn't do an exhaustive search.  Just grepped for "foreign".

**Comment by 3noch** [comment]
It's in the `#else` clause of each binding.
