### ISSUE TITLE
Support ADVANCED_OPTIMIZATIONS

### ISSUE THREAD

**Issue by 3noch** [reflex-frp/reflex-dom-semui#26]
All that is needed is modifying FFI to use `x['attr']` syntax instead of `x.attr`.

**Comment by 3noch** [comment]
I should note that this is issue is *cleverly* avoided when you add all the semantic-ui sources to the cabal file, as is done in this project. However, this leads to other annoying issues and is also far less flexible (you can't choose which semantic-ui modules to use, for example).

**Comment by mightybyte** [comment]
Thanks for the suggestion.  Check out the latest commit.

**Comment by 3noch** [comment]
Awesome! I was quite literally a couple hours too late in making one more comment:

You *also* need to construct the option objects using syntax like this:

```
opts = {};
opts['onChange'] = function() {...};
jQuery($...)['...'](opts);
```

because some of those fields still get renamed and GHCJS does not provide any way to preserve quotes on the field names (e.g. `{ "onChange": ... }`).
