### ISSUE TITLE
Checkbox setValue does not work

### ISSUE THREAD

**Issue by andrewthad** [reflex-frp/reflex-dom-semui#28]
The event for setting the value of a checkbox is never actually used. Consequently, it does not work.

**Comment by andrewthad** [comment]
Regression was introduced by https://github.com/reflex-frp/reflex-dom-semui/pull/23/files

**Comment by andrewthad** [comment]
Here's a PR that resolves the issue: https://github.com/reflex-frp/reflex-dom-semui/pull/29

**Comment by 3noch** [comment]
Thanks. I found this as well but forgot to send a PR.
